In [177]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [178]:
df = pd.read_csv("./heart_disease.csv")

df.head(5)

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140.0,289.0,0,Normal,172.0,N,0.0,Up,0
1,49,F,NAP,160.0,180.0,0,Normal,156.0,N,1.0,Flat,1
2,37,M,ATA,130.0,283.0,0,ST,98.0,N,0.0,Up,0
3,48,F,ASY,138.0,214.0,0,Normal,108.0,Y,1.5,Flat,1
4,54,M,NAP,150.0,195.0,0,Normal,122.0,N,0.0,Up,0

In [179]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    str
 2   ChestPainType   918 non-null    str
 3   RestingBP       914 non-null    float64
 4   Cholesterol     915 non-null    float64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    str
 7   MaxHR           916 non-null    float64
 8   ExerciseAngina  918 non-null    str
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    str
 11  HeartDisease    918 non-null    int64
dtypes: float64(4), int64(3), str(5)
memory usage: 86.2 KB

In [180]:
df.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,914.000000,915.000000,918.000000,916.000000,918.000000,918.000000
mean,53.510893,132.423414,198.702732,0.233115,136.804585,0.887364,0.553377
std,9.432617,18.474195,109.497795,0.423046,25.456660,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.500000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

In [181]:
df.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         4
Cholesterol       3
FastingBS         0
RestingECG        0
MaxHR             2
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [182]:
numeric_columns = df.select_dtypes(include=np.number).columns

df[numeric_columns] = df[numeric_columns].fillna(
    df[numeric_columns].median()
)

In [183]:
df.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [184]:
X = df.drop("HeartDisease", axis=1)
y = df["HeartDisease"]

In [185]:
X_numeric = X.select_dtypes(include=np.number)

print(X_numeric.head())

   Age  RestingBP  Cholesterol  FastingBS  MaxHR  Oldpeak
0   40      140.0        289.0          0  172.0      0.0
1   49      160.0        180.0          0  156.0      1.0
2   37      130.0        283.0          0   98.0      0.0
3   48      138.0        214.0          0  108.0      1.5
4   54      150.0        195.0          0  122.0      0.0

In [186]:
numeric_features = X.select_dtypes(include=np.number).columns
categorical_features = X.select_dtypes(exclude=np.number).columns

print("Numerical:", list(numeric_features))
print("Categorical:", list(categorical_features))

Numerical: ['Age', 'RestingBP', 'Cholesterol', 'FastingBS', 'MaxHR', 'Oldpeak']
Categorical: ['Sex', 'ChestPainType', 'RestingECG', 'ExerciseAngina', 'ST_Slope']

In [187]:
X_train, X_test, y_train, y_test = train_test_split(
    X_numeric,
    y,
    test_size=0.2,
    random_state=42
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

Training data: (734, 6)
Testing data: (184, 6)

In [188]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Features scaled successfully.")

Features scaled successfully.

In [189]:
# X_train_2d = X_train_scaled[:, :2]
# X_test_2d = X_test_scaled[:,:2]

svm_2d_models_new = {}

In [190]:
poly_svc = SVC(kernel="poly", degree=3)

poly_svc.fit(X_train_scaled, y_train)

y_pred_poly = poly_svc.predict(X_test_scaled)

print(f"Polynomial SVM Accuracy: {accuracy_score(y_test, y_pred_poly)}")

Polynomial SVM Accuracy: 0.7010869565217391

In [191]:
rbf_svc = SVC(kernel="rbf")

rbf_svc.fit(X_train_scaled, y_train)

y_pred_rbf = rbf_svc.predict(X_test_scaled)

print(f"RBF SVM Accuracy: {accuracy_score(y_test, y_pred_rbf)}")

RBF SVM Accuracy: 0.7336956521739131

In [192]:
linear_svc = SVC(kernel="linear")

linear_svc.fit(X_train_scaled, y_train)

y_pred_linear = linear_svc.predict(X_test_scaled)

print(f"Linear SVM Accuracy: {accuracy_score(y_test, y_pred_linear)}")

Linear SVM Accuracy: 0.717391304347826

In [ ]:

print("============= Linear SVM =============")
print(classification_report(y_test, y_pred_linear))

print("============= RBF SVM =============")
print(classification_report(y_test, y_pred_rbf))

print("============= Polynomial SVM =============")
print(classification_report(y_test, y_pred_poly))

============= Linear SVM =============
              precision    recall  f1-score   support

           0       0.63      0.77      0.69        77
           1       0.80      0.68      0.74       107

    accuracy                           0.72       184
   macro avg       0.72      0.72      0.72       184
weighted avg       0.73      0.72      0.72       184

============= RBF SVM =============
              precision    recall  f1-score   support

           0       0.65      0.79      0.71        77
           1       0.82      0.69      0.75       107

    accuracy                           0.73       184
   macro avg       0.74      0.74      0.73       184
weighted avg       0.75      0.73      0.74       184

============= Polynomial SVM =============
              precision    recall  f1-score   support

           0       0.60      0.88      0.71        77
           1       0.87      0.57      0.69       107

    accuracy                           0.70       184
   macro avg       0.73      0.73      0.70       184
weighted avg       0.76      0.70      0.70       184

In [194]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [195]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numeric_features),
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features)
    ]
)

X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

print("Preprocessing completed!")
print("Training shape:", X_train_processed.shape)
print("Testing shape:", X_test_processed.shape)

Preprocessing completed!
Training shape: (734, 20)
Testing shape: (184, 20)

In [196]:
linear_svc = SVC(kernel="linear")
rbf_svc = SVC(kernel="rbf")
poly_svc = SVC(kernel="poly", degree=3)

linear_svc.fit(X_train_processed, y_train)
rbf_svc.fit(X_train_processed, y_train)
poly_svc.fit(X_train_processed, y_train)

SVC(kernel='poly')

In [197]:
y_pred_linear = linear_svc.predict(X_test_processed)
y_pred_rbf = rbf_svc.predict(X_test_processed)
y_pred_poly = poly_svc.predict(X_test_processed)

In [ ]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

models = {
    "Linear SVM": y_pred_linear,
    "RBF SVM": y_pred_rbf,
    "Polynomial SVM": y_pred_poly
}

results = []

for name, prediction in models.items():
    results.append({
        "Model": name,
        "Accuracy": accuracy_score(y_test, prediction),
        "Precision": precision_score(y_test, prediction),
        "Recall": recall_score(y_test, prediction),
        "F1 Score": f1_score(y_test, prediction)
    })

results_df = pd.DataFrame(results)

results_df

            Model  Accuracy  Precision    Recall  F1 Score
0      Linear SVM  0.875000   0.855856  0.931373  0.892019
1         RBF SVM  0.896739   0.887850  0.931373  0.909091
2  Polynomial SVM  0.875000   0.883495  0.892157  0.887805

: